### ISSUE TITLE
Apple and email sign-in?

### ISSUE THREAD

**Issue by ghost** [ddikman/firebase-provider-stats#1]
Great script! It seems to be missing the Apple provider (public and anonymous) and the people who sign in with their email (password or passwordless). I do see from the export of Firebase that it's not clear information we can get for now, but I was wondering if you had thought of something?

**Comment by ddikman** [comment]
Hi @sofiashendi, thank you for your support and for raising this. I had completely missed this as I wrote the tool specifically to figure out number of Facebook logins.

I've added some code to try and figure out which are logged in with email compared to phone number but as you say, I am at the mercy of what the file provides. However, the apple login should appear in the provider list.

Alas, you are completely right about apple provider as well, really strange how that's not a part of the provider list. I might need to approach this stats extraction in a different way to get the full data.

Initially, I was working on creating a cloud function to iterate through the users and create the stats but it was hard to test so I thought this solution would be easier. Check it out if you're interested:

https://gist.github.com/ddikman/7dea60309a0799a45ebf50ef9e3d6dd9
